/*
DROP USER banking2 CASCADE;

CREATE USER banking2
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to banking2;
GRANT resource to banking2;
GRANT create session TO banking2;
GRANT create table TO banking2;
GRANT create view TO banking2;


conn banking2/p4ssw0rd

*/

/*******************************************************************************
   Create Tables
********************************************************************************/
DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT (
    ACCOUNTID        NUMBER NOT NULL,
    ACCOUNTBALANCE   NUMERIC(8,2),
    BANKCLIENTID     NUMBER,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNTID)
);
/

DROP TABLE BANKCLIENT;
CREATE TABLE BANKCLIENT (
    BANKCLIENTID   NUMBER NOT NULL,
    USERNAME       VARCHAR2(50),
    PASSWORD       VARCHAR2(50),
    CONSTRAINT PK_BANKCLIENT PRIMARY KEY (BANKCLIENTID)
);
/

DROP TABLE ADMIN;
CREATE TABLE ADMIN (
    ADMINID         NUMBER NOT NULL,
    ADMINUSERNAME   VARCHAR2(50),
    ADMINPASSWORD   VARCHAR2(50),
    CONSTRAINT PK_ADMIN PRIMARY KEY (ADMINID)
);
/

/************************************************************************************
    Foreign Key
*************************************************************************************/

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_BANKCLIENT 
    FOREIGN KEY (BANKCLIENTID) REFERENCES BANKCLIENT(BANKCLIENTID);
    
/************************************************************************************
    Auto-Increments
*************************************************************************************/
DROP SEQUENCE SQ_ACCOUNT_PK;
DROP SEQUENCE SQ_ADMIN_PK;
DROP SEQUENCE SQ_BANKCLIENT_PK;

CREATE SEQUENCE SQ_ACCOUNT_PK
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_ADMIN_PK
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_BANKCLIENT_PK
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_ACCOUNT
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
    SELECT SQ_ACCOUNT_PK.NEXTVAL INTO :NEW.ACCOUNTID FROM DUAL;    
END;
/

CREATE OR REPLACE TRIGGER TR_ADMIN
BEFORE INSERT ON ADMIN
FOR EACH ROW
BEGIN
    SELECT SQ_ADMIN_PK.NEXTVAL INTO :NEW.ADMINID FROM DUAL;    
END;
/

CREATE OR REPLACE TRIGGER TR_BANKCLIENT
BEFORE INSERT ON BANKCLIENT
FOR EACH ROW
BEGIN
    SELECT SQ_BANKCLIENT_PK.NEXTVAL INTO :NEW.BANKCLIENTID FROM DUAL;    
END;
/
        
/*************************************************************************************
    Insert
**************************************************************************************/

INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('Jordan123','Marvel2018!');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('Charlie@34','Winemaker@001!');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('Chrisburke18','Cscedept18@!');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('Mikemozer@1','Winemaker@001!');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('Tashiamha!2','Subaru!18');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('Fredashley!2','Bikes!sawesome12');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('coronafermin76','ThorRagnarok18!');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('lachuga@123','Revature18!');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('ryanpolar56','NeyYorkGiants');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('robertwells@!','NewEnglan18!');
INSERT INTO BANKCLIENT(USERNAME,PASSWORD) VALUES ('butts','butts');

--select * from bankclient;

/**************************************************************************************************
Insert into Account
***************************************************************************************************/

INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(500.00,2);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(1000.00,5);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(1500.00,7);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(2000.00,10);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(250.00,1);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(700.00,3);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(50000.00,9);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(9000.00,8);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(100.00,4);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(500.00,6);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(700.00,3);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(10.00,9);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(3.00,8);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(1.00,4);
INSERT INTO ACCOUNT(ACCOUNTBALANCE,BANKCLIENTID) VALUES(20.00,6);

--SELECT * FROM ACCOUNT ORDER BY BANKCLIENTID;

/********************************************************************************
INSERT INTO ADMIN
********************************************************************************/

INSERT INTO ADMIN(ADMINUSERNAME,ADMINPASSWORD) VALUES ('Robert','Welcome@123');
INSERT INTO ADMIN(ADMINUSERNAME,ADMINPASSWORD) VALUES ('Shivam','Password@123');

COMMIT;

--select * from admin;select * from account where ACCOUNT.BANKCLIENTID =1;

--select * from account LEFT JOIN BANKCLIENT ON ACCOUNT.BANKCLIENTID=BANKCLIENT.BANKCLIENTID ORDER BY ACCOUNTID;

UPDATE ACCOUNT
    SET ACCOUNTBALANCE = ACCOUNTBALANCE + 10
    WHERE ACCOUNTID = 20;