CREATE TABLE BEAR2 (
	BEAR_ID INTEGER PRIMARY KEY,
	BEAR_NAME VARCHAR2(100),
	BEAR_BIRTHDATE DATE,
	BEAR_WEIGHT NUMBER(5,2) DEFAULT 200.00,
	BEAR_TYPE_ID INTEGER NOT NULL,
	CAVE_ID INTEGER
);
/
CREATE TABLE BEAR2_TYPE (
    BEAR_TYPE_ID INTEGER PRIMARY KEY,
    BEAR_TYPE_NAME VARCHAR2(100)
);
/
CREATE TABLE CAVE2 (
    CAVE_ID INTEGER PRIMARY KEY,
    CAVE_NAME VARCHAR2(100),
    MAX_BEARS INTEGER DEFAULT 4
);
/
CREATE TABLE BEEHIVE2 (
    BEEHIVE_ID INTEGER PRIMARY KEY,
    BEEHIVE_WEIGHT NUMBER(5, 2) DEFAULT 75.00
);
/
CREATE TABLE BEAR2_BEEHIVE2 (
    BEAR_ID INTEGER,
    BEEHIVE_ID INTEGER,
    PRIMARY KEY (BEAR_ID, BEEHIVE_ID)
);
/

--FOREIGN KEY CONSTRAINTS
ALTER TABLE BEAR2
ADD CONSTRAINT FK_BEAR2_BEAR2_TYPE 
FOREIGN KEY (BEAR_TYPE_ID) REFERENCES BEAR2_TYPE(BEAR_TYPE_ID);
/
ALTER TABLE BEAR2
ADD CONSTRAINT FK_BEAR2_CAVE
FOREIGN KEY (CAVE_ID) REFERENCES CAVE2(CAVE_ID);
/
ALTER TABLE BEAR2_BEEHIVE2
ADD CONSTRAINT FK_BEAR2_BEAR2_BEEHIVE2
FOREIGN KEY (BEAR_ID) REFERENCES BEAR2(BEAR_ID);
/
ALTER TABLE BEAR2_BEEHIVE2
ADD CONSTRAINT FK_BEEHIVE2_BEAR2_BEEHIVE2
FOREIGN KEY (BEEHIVE_ID) REFERENCES BEEHIVE2(BEEHIVE_ID);
/

--ADD SOME DATA
INSERT INTO BEAR2_TYPE(BEAR_TYPE_ID,BEAR_TYPE_NAME) VALUES (1,'Grizzly');
INSERT INTO BEAR2_TYPE(BEAR_TYPE_ID,BEAR_TYPE_NAME) VALUES (2,'Polar');

INSERT ALL
INTO CAVE2 VALUES (1,'AWESOMECAVE1', 9) 
INTO CAVE2(CAVE_ID, CAVE_NAME) VALUES (2,'AWESOMECAVE2')
SELECT * FROM DUAL;




INSERT ALL
INTO BEAR2(BEAR_ID, BEAR_NAME, BEAR_BIRTHDATE, BEAR_TYPE_ID, CAVE_ID)
VALUES (3, 'Ferdinand', TO_DATE('1987-08-18 00:00:00', 'yyyy-mm-dd hh24:mi:ss'), 1, 2)
INTO BEAR2(BEAR_ID, BEAR_NAME, BEAR_BIRTHDATE, BEAR_TYPE_ID, CAVE_ID)
VALUES (8, 'Ernest', TO_DATE('1989-08-18 00:00:00', 'yyyy-mm-dd hh24:mi:ss'), 1, 1)
INTO BEAR2
VALUES (9, 'Elon', TO_DATE('1999-02-18 00:00:00', 'yyyy-mm-dd hh24:mi:ss'), 400.00, 2, 1)
INTO BEAR2
VALUES (10, 'Jeff', TO_DATE('1597-02-18 00:00:00', 'yyyy-mm-dd hh24:mi:ss'), 450.00, 2, 1)
SELECT * FROM DUAL;

INSERT ALL
INTO BEEHIVE2
VALUES (1, 100)
INTO BEEHIVE2
VALUES (2, 950)
INTO BEEHIVE2
VALUES (3, 125)
INTO BEEHIVE2
VALUES (4, 2)
SELECT * FROM DUAL;

INSERT ALL
INTO BEAR2_BEEHIVE2
VALUES (8, 1)
INTO BEAR2_BEEHIVE2
VALUES (8, 2)
INTO BEAR2_BEEHIVE2
VALUES (9, 4)
INTO BEAR2_BEEHIVE2
VALUES (3, 3)
INTO BEAR2_BEEHIVE2
VALUES (3, 2)
INTO BEAR2_BEEHIVE2
VALUES (3, 4)
INTO BEAR2_BEEHIVE2
VALUES (10, 1)
SELECT * FROM DUAL;

--ALTER TABLE

ALTER TABLE BEAR2_TYPE 
ADD SURVIVAL_PROCEDURE VARCHAR2(200);

--ADD SOME NEW VALUES FOR ALTERED COLUMN

UPDATE BEAR2_TYPE
SET SURVIVAL_PROCEDURE = 'play dead' WHERE BEAR_TYPE_ID = 1;


UPDATE BEAR2_TYPE
SET SURVIVAL_PROCEDURE = 'run downhill, then play dead' WHERE BEAR_TYPE_ID = 1;

UPDATE BEAR2_TYPE
SET SURVIVAL_PROCEDURE = 'lol none'
WHERE BEAR_TYPE_ID = 2;

---

INSERT INTO BEAR2
VALUES(92, 'Stacy', TO_DATE('1999-02-18 00:00:00', 'yyyy-mm-dd hh24:mi:ss'), 300.00, 1, null)

SELECT *--BEAR2.BEAR_ID, BEAR2.BEAR_NAME, CAVE2.CAVE_ID, CAVE2.CAVE_NAME 
FROM BEAR2 B
FULL OUTER JOIN CAVE2 ON B.CAVE_ID = CAVE2.CAVE_ID;