server:
  port: 8085
  
endpoints:
  beans:
    sensitive: false
  mappings:
    sensitive: false

spring:
  application:
    name: cat-app
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@aa-database.ckzkitpjrvtz.us-east-2.rds.amazonaws.com:1521:orcl
    username: rtcc6
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: ORACLE
    show-sql: true